### ISSUE TITLE
Method adjustments for dhuhr

### ISSUE THREAD

**Issue by digitalummah** [batoulapps/adhan-kotlin#13]
When comparing with other prayer time apps, the dhuhr times seems to be off by 1 min.

This is more a question than an issue: why is 1 min added to most of the method adjustments for dhuhr? It seems to be an intentional addition in the adhan library - just trying to understand the reason behind it.

Thanks!

**Comment by z3bi** [comment]
@digitalummah This is due to the Fiqh ruling that it is not allowed to pray at certain times (see [this list](https://islamqa.info/en/answers/48998/times-when-it-is-forbidden-to-pray)). One of those times is when the sun is exactly overhead. A lot of prayer time apps unfortunately calculate Dhuhr as exactly noon. A more correct approach would be to wait at least 1 minute for the sun to no longer be directly overhead.
