### ISSUE TITLE
Adding support for Tehran and Turkey

### ISSUE THREAD

**Issue by skkshoaib** [batoulapps/adhan-kotlin#59]
Salaam

I see that swift repo contains Tehran and turkey however such support doesn't exist in Android Library.

Any plan for supporting it?

I see reference to it here 3 years back but not implemented yet https://github.com/batoulapps/adhan-java/issues/14#issuecomment-650832911

Thanks

**Comment by ahmedre** [comment]
wa3laikum alsalam,
still need to go through and catch up with the Swift version. at the same time, this shouldn't be blocking support for Turkey, for example, since the API already allows setting custom angles as necessary by the developer, and since those methods don't actually do anything that the API isn't supporting today.

**Comment by ahmedre** [comment]
Istanbul method added in #63.
